env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
language: node_js
node_js:
  - '6'
before_script:
  - npm install -g bower grunt-cli
script: grunt linters test-unit-frontend test-unit-backend
